# Generated by Django 3.2.8 on 2022-02-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingZone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingArea',
            new_name='ParkingZone',
        ),
    ]
