# Generated by Django 3.2.8 on 2022-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingZone', '0003_auto_20220206_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='openingHours',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='rates',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='security',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='services',
            field=models.JSONField(default=[]),
        ),
    ]
