# Generated by Django 3.2.8 on 2022-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingZone', '0004_auto_20220206_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
