# Generated by Django 3.2.8 on 2022-02-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingZone', '0005_alter_parkingzone_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='latlong',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
